// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var EpisodeView, EpisodesListView, ViewHelper;
    ViewHelper = require('view_helper');
    EpisodeView = Marionette.ItemView.extend({
      tagName: 'li',
      template: ViewHelper.compile('<div class="episode-card" review_episode="1" data-src="{{vedioUrl}}"><img src="./assets/img/small/{{index}}.png"/><span class="watch">Watch</span><span class="episode-number">{{episodeNumber}}</span><span class="episode-title">{{name}}</span><span class="episode-description">{{description}}</span></div>'),
      events: {
        'mouseenter [review_episode]': 'enterEpisodeAction',
        'mouseleave [review_episode]': 'leaveEpisodeAction',
        'click': 'clickAction'
      },
      enterEpisodeAction: function() {
        console.log(111);
        this.$el.fadeTo(0, 1);
        return this.$el.find('.watch').show();
      },
      leaveEpisodeAction: function() {
        console.log(333);
        this.$el.fadeTo(0, 0.5);
        return this.$el.find('.watch').hide();
      },
      clickAction: function() {
        console.log(222);
        this.$el.fadeTo(0, 1);
        return this.$el.find('.watch').show();
      }
    });
    return EpisodesListView = Marionette.CompositeView.extend({
      className: 'episode-slider',
      template: ViewHelper.compile('<ul class="episode-list"></ul>'),
      childViewContainer: '.episode-list',
      childView: EpisodeView
    });
  });

}).call(this);
