// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var VedioView, ViewHelper;
    ViewHelper = require('view_helper');
    return VedioView = Marionette.LayoutView.extend({
      className: 'vedio',
      template: ViewHelper.compile('<img src="./assets/img/big/1.png" alt="..." class="img-rounded"><img src="./assets/img/play_1.png" alt="..." class="img-rounded" style="margin-top: -500px">'),
      events: {
        'click': 'playCurrentEpisodeAction'
      },
      onRender: function() {
        _.bindAll(this, 'playVideo');
        return App.app.commands.setHandler('play:vedio', this.playVideo);
      },
      onDestroy: function() {
        return App.app.commands.removeHandler('play:vedio', this.playVideo);
      },
      playVideo: function(vedioUrl) {
        var $vedioDom;
        if (vedioUrl == null) {
          vedioUrl = null;
        }
        if (!vedioUrl) {
          return;
        }
        $vedioDom = $('<embed src="" allowFullScreen="true" quality="high" width="600" height="500" align="middle" allowScriptAccess="always" type="application/x-shockwave-flash" flashvars="isAutoPlay=true"></embed>');
        $vedioDom.attr('src', vedioUrl);
        this.$el.html($vedioDom);
        return App.app.$scrollContainer.animate({
          scrollTop: 0
        }, 800);
      },
      playCurrentEpisodeAction: function() {
        var curEpiVedioUrl;
        curEpiVedioUrl = App.app.request('get:curEpiVedioUrl');
        return this.playVideo(curEpiVedioUrl);
      }
    });
  });

}).call(this);
