// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var VedioView, ViewHelper;
    ViewHelper = require('view_helper');
    return VedioView = Marionette.LayoutView.extend({
      className: 'vedio',
      template: ViewHelper.compile('<img src="./assets/img/big/1.png" alt="..." class="img-rounded"><img src="./assets/img/play_1.png" alt="..." class="img-rounded" style="margin-top: -500px">')
    });
  });

}).call(this);
